import pygame

SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1060
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)

CELL_WIDTH = 150
CELL_HEIGHT = 200
CELL_SIZE = (CELL_WIDTH, CELL_HEIGHT)

CARD_WIDTH = 120
CARD_HEIGHT = 180
CARD_SIZE = (CARD_WIDTH, CARD_HEIGHT)

FPS = 30

screen = pygame.display.set_mode(SCREEN_SIZE)

SKILL_WIDTH=200
SKILL_HEIGHT=160
SKILL_SIZE=(SKILL_WIDTH, SKILL_HEIGHT)