import pygame

SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)

CELL_WIDTH = 150
CELL_HEIGHT = 200
CELL_SIZE = (CELL_WIDTH, CELL_HEIGHT)

CARD_WIDTH = 120
CARD_HEIGHT = 180
CARD_SIZE = (CARD_WIDTH, CARD_HEIGHT)

FPS = 60

SKILL_WIDTH = 200
SKILL_HEIGHT = 160
SKILL_SIZE = (SKILL_WIDTH, SKILL_HEIGHT)


# 게임판 위 위치를 실제 위치로 변환
def transform_pos(pos):
    j, i = pos
    return (30 - CELL_WIDTH / 2 + (CARD_WIDTH + 30) * i, 30 - CELL_HEIGHT / 2 - 35 + (CELL_HEIGHT + 10) * j)


BUFF_WIDTH = 120
BUFF_HEIGHT = 160

FLAG_EMPTY = 0
FLAG_PLAYER_TEAM = 1
FLAG_ENEMY_TEAM = 2
FLAG_SUMMONS = 3

TAG_NORMAL_ATTACK = "normal attack"
TAG_SKILL = "skill"
TAG_SPECIAL_SKILL = "special skill"
TAG_PENETRATE = "penetrate hit"
TAG_HEAL = "heal"
TAG_SUMMON = "summon"
TAG_BUFF = "buff"
TAG_FIRE = "fire"
